### ISSUE TITLE
Nonetype attribute error while following code example

### ISSUE THREAD

**Issue by TARDIInsanity** [ahira-justice/chess-board#4]
I encountered a Nonetype error that is (presumably) a result of a fault within the included display.py file. One function "start(fen='')" sets a new variable gameboard, but does not set it to the proper type for the following "update(fen)" function to use it. I used:
`board = display.start(validfen)
while not(display.checkForQuit()):
    board = display.update(validfen, board)
    time.sleep(0.1)`
which returned a methods error; Nonetype object does not have method displayBoard. I also notice that board is imported from ., which is concerning. Where does it get board from? What is the board class?

**Comment by robotrobo** [comment]
i think its the same issue as #2 (now closed),  i issued a PR regarding the same.

**Comment by ahira-justice** [comment]
Fixed

See https://github.com/ahira-justice/chess-board/pull/5#issuecomment-1030420625
