### ISSUE TITLE
Please update library to allow the board to flip if a player chooses to play as black

### ISSUE THREAD

**Issue by kiraksi** [ahira-justice/chess-board#9]
Please add a method to the board that will render it upside down from black's POV if we enter it as a parameter. Also thank you for responding to my email and feel free to do this whenever you have time! Thank you

**Comment by ahira-justice** [comment]
Hi @kira-kaur-sidhu,

I just published v0.4.0 that includes this feature. Try it out and let me know if there are any issues with it. Cheers!
